@startuml
' FSM for simple forwarder contract

state Exit {
 [*] --> Refund
 [*] --> Withdrawal

 Refund --> Refund: ERC20.Transfer
 Withdrawal --> Withdrawal: ERC20.Transfer
}

[*] --> Ready : constructor(initialOwner, tokenContract)
Ready --> Forwarding: TxIn
Forwarding --> Forwarding: ERC20.Transfer
Forwarding --> Exit: TxOut

Refund --> [*]: Event\nRefund(hashlock)
Withdrawal --> [*]: Event\nWithdraw(hashlock);
@enduml
