@startuml
skinparam BoxPadding 20

legend top
HashedTimelockERC20 contract: sender withdraws refund after timelock expiry
end legend

box "Ethereum Network" #A9C5E6
participant Counterparty as counterparty << Account >>
participant Router as router << Account >>
participant ForwardHashedTimelockERC20 as htlc << HTLC >>
participant ERC20Contract as token << Token >>
participant Events as events
end box

note left of htlc
Constructor:
  address tokenContract;
  uint tokenDecimals;
  uint minRoutingAmount;
end note

counterparty->token:approve(htlc address, amount)
token->counterparty
counterparty->htlc:route(\n\tincoming\n\tcounterparty,\n\thashlock,\n\ttimelock,\n\ttokenContract,\n\tamount\n)

activate htlc
  htlc->token:transferFrom(counterparty, htlc address, amount)
  token->htlc
  htlc->events:HTLCERC20New(locks, values, etc.)
  htlc->counterparty:hashlock
deactivate htlc

counterparty->counterparty:receiver does nothing\nafter timelock seconds:\nCONTRACT EXPIRES

counterparty->htlc:refund()

activate htlc
  htlc->token:transfer(counterparty, amount)
  token->htlc
  htlc->events:HTLCERC20Refund(contracted)
deactivate htlc

token->counterparty:receives refunded tokens
@enduml