@startuml
skinparam BoxPadding 20

legend top
\t\t\t\tHashedTimelockERC20 Contract: **Incoming** Flow
(Router settles with preimage before the timelock expires and funds remain on the contract)
end legend

box "Ethereum Network" #A9C5E6
participant Counterparty as counterparty << Account >>
participant Router as router << Account >>
participant ForwardHashedTimelockERC20 as htlc << HTLC >>
participant ERC20Contract as token << Token >>
participant Events as events
end box

note left of htlc
Constructor:
  address tokenContract;
  uint tokenDecimals;
  uint minRoutingAmount;
end note

counterparty->counterparty:generates BOLT11, takes hashlock

counterparty->token:approve(htlc address, amount)
token->counterparty

counterparty->htlc:route(\n\tincoming\n\tcounterparty,\n\tamount,\n\ttimelock,\n\thashlock\n)

note right of htlc
State stored:
  bool incoming;
  address counterparty;
  uint amount;
  bytes32 hashlock;
  uint timelock; // UNIX ts
end note

activate htlc
  htlc->token:transferFrom(counterparty, htlc address, amount)
  token->htlc
  htlc->events:HTLCERC20New(locks, values, etc.)
  htlc->router:hashlock
deactivate htlc

counterparty->router:submits BOLT11
router->router:checks hashlock vs BOLT11 payment_hash
router->counterparty:pays and obtains secret preimage\n[sha256(secret preimage) == hashlock]

router->htlc:settle(secret preimage)

activate htlc
  htlc->events:HTLCERC20Settle(secret preimage)
  htlc->htlc:funds stay in contract for Outgoing swap
deactivate htlc
@enduml