@startuml
skinparam BoxPadding 20

legend top
\t\t\t\tHashedTimelockERC20 Contract: **Outgoing** Flow
(Router settles with preimage before the timelock expires and funds remain on the contract)
end legend

box "Ethereum Network" #A9C5E6
participant Counterparty as counterparty << Account >>
participant Router as router << Account >>
participant ForwardHashedTimelockERC20 as htlc << Smart Contract >>
participant ERC20Contract as token << Smart Contract >>
participant Events as events
end box

note right of htlc
State stored:
  bool incoming;
  address counterparty;
  address tokenContract;
  uint amount;
  bytes32 hashlock;
  uint timelock; // UNIX ts
end note

router->counterparty:sends fee invoice (DDOS protection)
counterparty->router:pays fee

router->htlc:RequestRouting(\n\tincoming\n\tcounterparty,\n\thashlock,\n\ttimelock,\n\ttokenContract,\n\tamount\n)

activate htlc
  htlc->events:LogHTLCERC20New(locks, values, etc.)
  htlc->router:hashlock
deactivate htlc

router->counterparty:sends BOLT11 with hashlock

activate counterparty
  counterparty->counterparty:verifies contract hashlock & timelock
  counterparty->router:pays BOLT11
deactivate counterparty

router->counterparty:reveals preimage\n[sha256(secret preimage) == hashlock]

counterparty->htlc:settle(secret preimage)
activate htlc
  htlc->token:transfer(counterparty, amount)
  token->htlc
  htlc->events:LogHTLCERC20Withdraw(secret preimage)
deactivate htlc

token->counterparty:counterparty receives tokens

@enduml